spring:
  datasource:
    #    url: jdbc:mysql://mysql:3306/student_mis?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://localhost:3306/student_mis?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    type: redis
  redis:
    #    host: redis
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
#server:
#  port: 8081
server:
  port: 8443

logging:
  level:
    root: info
    com:
      zrh: debug
  file:
    name: logs/app.out.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM-dd}/app.out.%i.log
      max-history: 30
      clean-history-on-start: false
      max-file-size: 10MB

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0
swagger:
  base-package: com.zrh.controller
  description: 课程管理系统
  version: 1.0
  enabled: true
minio:
  #  url: http://minio:9000
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: course-mng